// eslint-disable-next-line import/no-anonymous-default-export
export default {
  login: "likeri29",
  id: 104503014,
  node_id: "U_kgDOBjqW5g",
  avatar_url: "https://avatars.githubusercontent.com/u/104503014?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/likeri29",
  html_url: "https://github.com/likeri29",
  followers_url: "https://api.github.com/users/likeri29/followers",
  following_url: "https://api.github.com/users/likeri29/following{/other_user}",
  gists_url: "https://api.github.com/users/likeri29/gists{/gist_id}",
  starred_url: "https://api.github.com/users/likeri29/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/likeri29/subscriptions",
  organizations_url: "https://api.github.com/users/likeri29/orgs",
  repos_url: "https://api.github.com/users/likeri29/repos",
  events_url: "https://api.github.com/users/likeri29/events{/privacy}",
  received_events_url: "https://api.github.com/users/likeri29/received_events",
  type: "User",
  site_admin: false,
  name: "Stanislav Pochtaruk",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 8,
  public_gists: 0,
  followers: 3,
  following: 6,
  created_at: "2022-04-27T11:44:54Z",
  updated_at: "2023-10-04T20:29:37Z",
};
